[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.20"

[rpc_endpoints]
sepolia = "https://sepolia.infura.io/v3/${INFURA_KEY}"
goerli = "https://goerli.infura.io/v3/${INFURA_KEY}"
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
localhost = "http://127.0.0.1:8545"

[etherscan]
sepolia = { key = "${ETHERSCAN_KEY}" }
goerli = { key = "${ETHERSCAN_KEY}" }
mainnet = { key = "${ETHERSCAN_KEY}" }
